image: "golang:1.13.10-buster"

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - formatting
  - testing
  - building
  - deploying

gofmt:
  stage: formatting
  only:
    - master
    - merge_requests
  before_script: []
  script:
    - test -z $(gofmt -l -s .)

test_bot:
  stage: testing
  extends: .go-cache
  services:
    - postgres:12-alpine
  only:
    - master
    - merge_requests
  variables:
    IS_CI_TEST: "true"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: 5432
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "test"
    POSTGRES_PASSWORD: "postgres"
  script:
    - cd bot
    - cat $ENV_FILE > .env
    - go test -cover -coverprofile=coverage.out ./...
    - go tool cover -func coverage.out
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'

test_vk_library:
  stage: testing
  extends: .go-cache
  only:
    - master
    - merge_requests
  script:
    - cd vk
    - go test -cover -coverprofile=coverage.out -coverpkg=./  ./...
    - go tool cover -func coverage.out
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'

build:
  stage: building
  image: docker:19.03.5
  services:
    - docker:dind
  when: manual
  only:
    - master
    - merge_requests
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploying
  when: manual
  tags:
    - server
  only:
    - master
    - merge_requests
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - mkdir -pv ~/projects/khti_timetable_bot && mkdir -pv ~/projects/khti_timetable_bot/db/migrations
  script:
    - cp $CI_PROJECT_DIR/docker-compose.yml ~/projects/khti_timetable_bot/docker-compose.yml
    - cp $CI_PROJECT_DIR/bot/db/migrations/* ~/projects/khti_timetable_bot/db/migrations/
    - cat $ENV_FILE > ~/projects/khti_timetable_bot/.env
    - cd ~/projects/khti_timetable_bot
    - docker-compose pull
    - docker-compose down
    - docker image prune -f
    - docker-compose up -d
