image: "golang:1.13.10-buster"

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - formatting
  - testing
  - building
  - deploying

gofmt:
  stage: formatting
  only:
    - master
    - merge_requests
  before_script: []
  script:
    - test -z $(gofmt -l -s .)

test_bot:
  stage: testing
  extends: .go-cache
  only:
    - master
    - merge_requests
  script:
    - cd bot
    - go test -cover -coverprofile=coverage.out ./...
    - go tool cover -func coverage.out
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'

test_vk_library:
  stage: testing
  extends: .go-cache
  only:
    - master
    - merge_requests
  script:
    - cd vk
    - go test -cover -coverprofile=coverage.out -coverpkg=./  ./...
    - go tool cover -func coverage.out
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'

build:
  stage: building
  extends: .go-cache
  when: manual
  only:
    - master
    - merge_requests
  script:
    - echo "Building..."


deploy:
  stage: deploying
  extends: .go-cache
  when: manual
  only:
    - master
    - merge_requests
  script:
    - echo "Deploying..."
